name: Format, Build and Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Check formatting using Spotless
        run: mvn -B spotless:check --file pom.xml


  build:
    needs : formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B compile --file pom.xml


  test:
    needs : build
    runs-on: ubuntu-latest
    env:
      FLOPPA_MONGO_CLUSTER_URL: "mongodb://localhost:27017"
      FLOPPA_MONGO_DATABASE : ${{ secrets.FLOPPA_MONGO_DATABASE }}
      FLOPPA_HOST_EMAIL : ${{ secrets.FLOPPA_HOST_EMAIL }}
      FLOPPA_HOST_PASSWORD : ${{ secrets.FLOPPA_HOST_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
           mongodb-version: '6.0'
      - name: Tests with Maven
        run: mvn -B verify --file pom.xml
