name: Runs tests using Maven

on:
  workflow_call:
    inputs:
      item-ref:
        required: false
        default: ''
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.item-ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Tests
        run: mvn -B test --file pom.xml