name: Runs tests using Maven

on:
  workflow_call:
    inputs:
      item-ref:
        required: false
        default: ''
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLOPPA_MONGO_CLUSTER_URL: "mongodb://localhost:27017"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.item-ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      - name: Tests
        run: mvn -B verify --file pom.xml