name: Packaging for the production environment

on:
  workflow_dispatch:
    inputs:
      item-ref:
        description: 'commit, tag ou branch à package'
        required: true
        default: ''
        type: string

jobs:
  run-tests:
    uses: ./.github/workflows/maven-test.yml
    with:
      item-ref: ${{ inputs.item-ref }}

  docker-build:
    needs: run-tests
    uses: ./.github/workflows/docker-build.yml
    with:
      item-ref: ${{ inputs.item-ref }}
    secrets:
      cluster-url: ${{ secrets.FLOPPA_MONGO_PRODUCTION_CLUSTER_URL }}
      database-name: ${{ secrets.FLOPPA_MONGO_PRODUCTION_DATABASE }}
